### ISSUE TITLE
Problem with MembershipRebootUserService and requireAccountVerification="true" and External Provider

### ISSUE THREAD

**Issue by LeandroPT** [IdentityServer/IdentityServer3.MembershipReboot#20]
Hello,

Today i was configuring ADFS, and got a problem with the way MembershipRebootUserService.ProcessNewExternalAccountAsync is implemented.

When Membershipreboot had the option requireAccountVerification="true" after a sucessfull authentication the user is not created with the error :
```
Warning: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 
19/03/2015 15:59:52 +00:00 -- user service returned error message: Email is required
```

The reason of this is that even though the claim is provided, the method ProcessNewExternalAccountAsync is not considering it:
```
user = userAccountService.CreateAccount(
                tenant,
                Guid.NewGuid().ToString("N"), 
                null, null,
                null, null, 
                user);
```

I fixed it by creating a custom UserService... Is this the intention?

Probably it should be:
```
user = userAccountService.CreateAccount(
                tenant,
                Guid.NewGuid().ToString("N"), 
                null, ClaimHelper.GetValue(claims, Constants.ClaimTypes.Email),
                null, null, 
                user);
```
Thanks,
Leandro

**Comment by brockallen** [comment]
Yep, I ran across this the other day myself. I'd agree it's a bug.

**Comment by brockallen** [comment]
Ok, finally got around to making this change. Thanks.

**Comment by SourceStudio** [comment]
Hi,

May I ask when this change will be released?

Thanks,

Mark

**Comment by brockallen** [comment]
I suspect I did this on the dev branch, so it'll be part of the 2.0.0 release. I'm guessing, but I think we're releasing it in the next month.
