### ISSUE TITLE
GetClaimsForAuthenticateResult vs. GetClaimsFromAccount

### ISSUE THREAD

**Issue by stevenfirstrowinc** [IdentityServer/IdentityServer3.MembershipReboot#21]
Please will you describe the use cases for these two methods?

1) GetClaimsFromAccount - Only used when calling the user profile.
2) GetClaimsForAuthenticateResult - Only used during AuthenticateLocalAsync

**Comment by brockallen** [comment]
1. It's a virtual to map from the account class to claims.
2. It's a virtual to add claims to the AuthenticateResult.

**Comment by stevenfirstrowinc** [comment]
hmmm.  Could you perhaps add a bit more color?  

1) When I authenticate, I already get the claims that user has stored in their account claims.  Is this a way to add something that maybe isn't directly related to that account but needs to be in the claims?

2) I guess this is something specific for when a user authenticates but maybe you could provide an example?

**Comment by brockallen** [comment]
Well, look at the implementations to see how they fit in (https://github.com/IdentityServer/IdentityServer3.MembershipReboot/blob/master/source/MembershipRebootUserService/MembershipRebootUserService.cs). It's not overly complicated, but if it's over engineered for what you want then perhaps just implement the `IUserService` directly.

**Comment by stevenfirstrowinc** [comment]
Sorry, yes I looked at the implementation that's how I know that it works the way i described above.  I'm just trying to understand when I would want claims that are for AuthenticationResult vs. for  an Account.  A simple example to use to get my head around it.

**Comment by brockallen** [comment]
GetClaimsFromAccount would be used if you added custom properties to the UserAccount-derived class that you needed to be included int he claims.

GetClaimsForAuthenticateResult is if you need anything beyond sub and name claims in the IdentityServer cookie, which are used to populate the claims principal passed to the other user service APIs (like IsActive, GetProfile, Logout, etc).

**Comment by stevenfirstrowinc** [comment]
GetClaimsForAuthenticateResult - I think I see now.  For example if I needed some additional information to get the user's profile, I could pass it along in the cookie via this method then use it when getting profile information later.

**Comment by brockallen** [comment]
Yep -- and that's less a feature of MR and more a feature of just how the user service works in IdSvr.

**Comment by stevenfirstrowinc** [comment]
got it.  many thanks for sticking with it for me.
