### ISSUE TITLE
Retrieving CustomUser Properties

### ISSUE THREAD

**Issue by rndthoughts** [IdentityServer/IdentityServer3.MembershipReboot#24]
I can't seem to retrieve the FirstName, LastName and Age property values as specified on the virtual properties in CustomUser? I am trying to modify the "GetClaimsFromAccount" function in the MembershipRebootService to do this and I can see the CustomUser EntityFramework proxy class in the debugger and it's associated properties but not access them?

**Comment by brockallen** [comment]
You need to manually map those when a token is requested. This can be done via one of the virtuals from the MRUserAccountService base class.

**Comment by rndthoughts** [comment]
Thanks Brock, I think i got it.  If I'm right, I need to do this:

      public class CustomUserAccountService : UserAccountService<CustomUser>
      {
        public CustomUserAccountService(CustomConfig config, CustomUserRepository repo)
            : base(config, repo)
        {
        }

        public override IEnumerable<Claim> MapClaims(CustomUser account)
        {
            var claims = new List<Claim>();

            if (!string.IsNullOrWhiteSpace(account.FirstName))
            {
                claims.Add(new Claim(Constants.ClaimTypes.GivenName, account.FirstName));
            }

            return claims;
        }
    }

**Comment by brockallen** [comment]
That's another way as well
