### ISSUE TITLE
show locked error message

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer3.MembershipReboot#25]

**Comment by j--w** [comment]
Was just looking for some documentation on this and saw you closed this issue 35 minutes ago. Is there no support for an error message when a user is locked out from too many failed logins?

**Comment by brockallen** [comment]
Yea, I closed it because right now MR doesn't have a good API to allow the app to detect this. MR does it internally, though... just not public API for it.

**Comment by brockallen** [comment]
I guess we could replicate that logic tho in this lib.... ok, i'll check on it.

**Comment by brockallen** [comment]
Also, I'm not doing that in the AspId repo either.

**Comment by j--w** [comment]
Thanks for the quick update. I think firing an email with the TooManyRecentPasswordFailuresEvent is better for my use case anyway, mostly was just curious.
