### ISSUE TITLE
Login with email address

### ISSUE THREAD

**Issue by AlexandreRoba** [IdentityServer/IdentityServer3.MembershipReboot#26]
Dear all,

I have setup membershipreboot and configured it to use the email as username.
This scenario does not seem to be supported by the MembershipRebootUserService. Is this correct?
If so will it be supported or should I overwrite the AuthotenticateLocalAsync and perform a conversion trick in there.

Thanks for any help you can provide me with.

Alexandre

**Comment by brockallen** [comment]
Do you have the MR configuration class configured to use email as username?

**Comment by brockallen** [comment]
Any update?

**Comment by AlexandreRoba** [comment]
Dear,
Thanks for the follow. I was using the wrong configuration. Everithing seems to be working fine.
Regards.
Alex


Sent from my Samsung device

-------- Original message --------
