### ISSUE TITLE
ReflectionTypeLoadException in ScopeRequirementMiddleware.cs

### ISSUE THREAD

**Issue by kylegalbraith** [IdentityServer/IdentityServer3.MembershipReboot#27]
I am trying to unit test some service endpoints that utilize MembershipReboot to create users. I have created an interface to go over UserAccountService so that I can mock the calls to MR to send back the appropriate stuff. Below is what I have setup for CustomUser, CustomUserAccountService, and CustomUserRepository:
```c#
public class CustomUser : RelationalUserAccount
    {
        [Display(Name = "First Name")]
        public virtual string FirstName { get; set; }
        [Display(Name = "Last Name")]
        public virtual string LastName { get; set; }
    }

    public class CustomUserAccountService : UserAccountService<CustomUser>, ICustomUserAccountService<CustomUser>
    {
        public CustomUserAccountService(CustomConfig config, CustomUserRepository repo)
            : base(config, repo)
        {
        }
    }

    public class CustomUserRepository : DbContextUserAccountRepository<CustomDatabase, CustomUser>, ICustomUserRepository
    {
        public CustomUserRepository(CustomDatabase ctx)
            : base(ctx)
        {
        }
    }
```
When I first boot up I get a ReflectionTypeLoadException within ScopeRequirementMiddleware.cs. If I continue past this exception I end up getting a TypeLoadException stating that CustomUserAccountService does not implement the method 'GetValidationMessage'.

I am a bit confused on why this does not work, the interface is just a wrapper and the parent class UserAccountService actually implements the GetValidationMessage so why is it even looking in CustomUserAccountService?

**Comment by brockallen** [comment]
Is the scope middleware configured with an array of strings or something else for the scopes?

**Comment by kylegalbraith** [comment]
Are you referring to the RequiredScopes for the API or the actual scopes defined within IdentityServer?

```c#
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
{
     Authority = idProviderUrl,
     RequiredScopes = new[] { "MyAPI" }
});
```

**Comment by brockallen** [comment]
Yes, please try string[].

**Comment by kylegalbraith** [comment]
Still get the exception....
```c#
string[] scopes = {"MyAPI"};
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
{
      Authority = idProviderUrl,
      RequiredScopes = scopes
});

```

**Comment by brockallen** [comment]
Are you loading from NuGet or MyGet? What's the package ID and source? // @leastprivilege

**Comment by kylegalbraith** [comment]
Loading from Nuget. IdentityServer package ID is Thinktecture.IdentityServer3 and I am also using Thinktecture.IdentityServer3.MembershipReboot gotten from Nuget as well.

It is worth noting that I have a class library that holds the CustomConfig, CustomDatabase, CustomUser, and interfaces that is then referenced in both my API and in my IdentityServer project. Within this class library I make use of the BrockAllen.MembershipReboot and BrockAllen.MembershipReboot.Ef

**Comment by brockallen** [comment]
Ok, I'll try to repro when I get some time later this week.

**Comment by kylegalbraith** [comment]
Thank you, if you need more details please let me know.

**Comment by brockallen** [comment]
Did this ever get sorted out?

**Comment by kylegalbraith** [comment]
Yes, I ended up finding a way to mock the user service calls in my unit tests. Turns out there was no need to create the interfaces to this because you guys had already made life easy my making the methods virtual. Thanks for the awesome work @brockallen.

**Comment by brockallen** [comment]
Ok, sorry I didn't follow your original question. Glad you're all set now.
