### ISSUE TITLE
Configuring MR for sending emails

### ISSUE THREAD

**Issue by kylegalbraith** [IdentityServer/IdentityServer3.MembershipReboot#28]
I am trying to implement MR to send out an email per the documentation over [here](https://github.com/brockallen/BrockAllen.MembershipReboot/wiki/Email-Configuration) and have added the following to my app.config
```
<system.net>
    <mailSettings>
      <smtp deliveryMethod="SpecifiedPickupDirectory">
        <specifiedPickupDirectory pickupDirectoryLocation="c:\temp\maildrop\" />
      </smtp>
    </mailSettings>
</system.net>
```

And in my CustomConfig per the [this sample project](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/MembershipReboot/SelfHost/MR/CustomConfig.cs) I have added the following....
```C#
    public class CustomConfig : MembershipRebootConfiguration<CustomUser>
    {
        public static readonly CustomConfig Config;

        static CustomConfig()
        {
            Config = new CustomConfig();
            Config.PasswordHashingIterationCount = 10000;
            Config.RequireAccountVerification = false;
            Config.EmailIsUsername = true;

            var em = new EmailMessageFormatter<CustomUser>(new RelativePathApplicationInformation()
            {
                ApplicationName = "Test",
                EmailSignature = "Test Signature",
                RelativeCancelVerificationUrl = "UserAccount/Register/Cancel/",
                RelativeConfirmChangeEmailUrl = "UserAccount/ChangeEmail/Confirm/",
                RelativeConfirmPasswordResetUrl = "UserAccount/PasswordReset/Confirm/",
                RelativeLoginUrl = "UserAccount/Login",
            });
            
            Config.AddEventHandler(new EmailAccountEventsHandler<CustomUser>(em));
            
        }
    }
```

Yet when I try a simple method such as SendTwoFactorAuthenticationCode no email shows up in the directory I specified. Any tips on what I am missing and what approach I need to take....

**Comment by brockallen** [comment]
Hmm, I suspect you're getting errors since `RelativePathApplicationInformation` throws in `GetApplicationBaseUrl` (which means it should be abstract, but that's a different conversation). You need to use the OWIN version which is `OwinApplicationInformation`.

**Comment by kylegalbraith** [comment]
@brockallen thanks for getting back to me. It appears that OwinApplicationInformation expects an IAppBuilder as the first parameter, but as I am setting this up inside of CustomConfig, I do not have one. Does that mean I should be wiring this up in the Startup.cs?

**Comment by brockallen** [comment]
Yes -- it needs to capture the request so it can build the full URLs to the various pages.

**Comment by kylegalbraith** [comment]
Hmm I am using CustomConfig, which gets set up with out in Startup.cs
```c#
var idsvrFactory = Factory.Configure();
idsvrFactory.ConfigureCustomUserService(connectionString);
```

In ConfigureCustomUserService it sets up CustomConfig
```c#
public static void ConfigureCustomUserService(this IdentityServerServiceFactory factory, string connString)
 {
        factory.UserService = new Registration<IUserService, CustomUserService>();
        factory.Register(new Registration<CustomUserAccountService>());
        factory.Register(new Registration<CustomConfig>(CustomConfig.Config));
        factory.Register(new Registration<CustomUserRepository>());
       factory.Register(new Registration<CustomDatabase>(resolver => new CustomDatabase(connString)));
 }
```

So in CustomConfig I have no access to IAppBuilder in order to use the OwinApplicationInformation and additionally I am not sure if I need to do any binding like is done in the documentation...
```c#
public class CustomConfig : MembershipRebootConfiguration<CustomUser>
    {
        public static readonly CustomConfig Config;

        static CustomConfig()
        {
            Config = new CustomConfig();
            Config.PasswordHashingIterationCount = 10000;
            Config.RequireAccountVerification = false;
            Config.EmailIsUsername = true;

            //pass app in as a parameter?
            var oai = new OwinApplicationInformation(app, "Test", "Test Signature", "UserAccount/Login", "UserAccount/ChangeEmail/Confirm/", "UserAccount/Register/Cancel/", "UserAccount/PasswordReset/Confirm/");
            var em = new EmailMessageFormatter<CustomUser>(oai);
            
            Config.AddEventHandler(new EmailAccountEventsHandler<CustomUser>(em));
            
            //where to bind now?
        }
    }
```

I tried passing app into the ConfigureCustomUserService so I could then pass it along to CustomConfig to complete that there, but that produced no email as well...Just for clarity I am just trying to dump the email into a local directory per my web.config in my original posting.

**Comment by brockallen** [comment]
Any update?
