### ISSUE TITLE
Missing Method Exception UserAccountService.CreateAccount for External Provider

### ISSUE THREAD

**Issue by lehne** [IdentityServer/IdentityServer3.MembershipReboot#30]
When I use ADFS as an external provider and configure Membership Reboot as the user service in IdentityServer, I get an error (Log is below) that indicates that the CreateAccount method signature shown below is not found. I copied the Samples repository for how to implement MembershipReboot with IdSvr3. The only thing that is different is that I am using ADFS as an AuthenticationOption. I log in with my credentials in the ADFS provider and am redirected back to IdSvr3 (getting the error "There was an unexpected error"). Any ideas?

>w3wp.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 8/5/2015 5:38:08 PM +00:00 -- Callback invoked from external identity provider
w3wp.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 8/5/2015 5:38:08 PM +00:00 -- external user provider: adfs, provider ID: n1QfLgGMj2CqYoU2C_gzhTFm4n6sZWouTjKjxkUGjX4
w3wp.exe Error: 0 : [Thinktecture.IdentityServer.Core.Configuration.Hosting.LogProviderExceptionLogger]: 8/5/2015 5:38:08 PM +00:00 -- Unhandled exception
System.MissingMethodException: Method not found: 'System.__Canon BrockAllen.MembershipReboot.UserAccountService`1.CreateAccount(System.String, System.String, System.String, System.String, System.Nullable`1<System.Guid>, System.Nullable`1<System.DateTime>, System.__Canon)'.
   at Thinktecture.IdentityServer.MembershipReboot.MembershipRebootUserService`1.<ProcessNewExternalAccountAsync>d__21.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Thinktecture.IdentityServer.MembershipReboot.MembershipRebootUserService`1.ProcessNewExternalAccountAsync(String tenant, String provider, String providerId, IEnumerable`1 claims)
   at Thinktecture.IdentityServer.MembershipReboot.MembershipRebootUserService`1.<AuthenticateExternalAsync>d__1c.MoveNext()

**Comment by brockallen** [comment]
Yep, thanks -- I'm looking into this now.

**Comment by lehne** [comment]
Thanks! I did add some custom properties to my Custom UserAccount entity. Would this cause a problem?

**Comment by brockallen** [comment]
Did you upgrade to MR 1.8.4?

**Comment by lehne** [comment]
Yes, I'm thinking it might be an issue with EF.

**Comment by brockallen** [comment]
I think the error you're seeing is when you use IdentityManager, right?

**Comment by lehne** [comment]
Yes, it is when I use IdentityManager or IdentityServer. I think I've screwed up all of the migrations. I wanted to use a one context for MembershipReboot (in IdentityServer) and then keep all of my business data in another context (but still access the tables referenced by MembershipReboot).  I think I incorrectly referenced the Entity types used in MembershipReboot. Is there a way to reuse those types (UserAccount, TwoFactorAuthTokens, etc)?

**Comment by brockallen** [comment]
I am in the process up dating IdMgr to 8.4 of MR -- I think that's the issue.

**Comment by lehne** [comment]
That might be it. I tried downgrading MR to 8.2 and I was still getting an issue. I didn't try downgrading any further, however.

**Comment by lehne** [comment]
I just tested Adding a user in IdentityManager and got the same error. It is the 'CreateAccount' method again. Creating a role worked fine.

**Comment by brockallen** [comment]
I just updated all the IdMgr nugets, and the IdSvr3.MR mygets -- mind trying to update and see if the problem goes away? 

I think the real problem was just assembly version mismatches

**Comment by lehne** [comment]
I updated and IdentityManager now works as expected but I am still not able to get the external ADFS provider to create an account.

**Comment by brockallen** [comment]
Ok, that might be something else. I'm going to close this issue since I think the initial error reported was related to the versioning mismatch from MR 8.4. Please investigate some more and open a new issue for the ADFS problem. Thx.

**Comment by lehne** [comment]
Thanks, Brock!

**Comment by lehne** [comment]
Upgrading to IdentityServer3 v2 solved it! Great work @brockallen!
