### ISSUE TITLE
Setting up MRB with CustomUserDetails and IdentitySever

### ISSUE THREAD

**Issue by shaneprice** [IdentityServer/IdentityServer3.MembershipReboot#31]
I am trying to setup an application that uses MRB with IdentityServer3 with custom UserAccount details.....ohhh and I have thrown Autofac into the mix for DI

I am trying to use the examples from both IdentityServer & MRB to get what I want working but not having much joy.

To better explain I thought I might do a small code dump

I have a CustomUser model 

    public class CustomUserAccount : RelationalUserAccount
    {
        // make sure the custom properties are all virtual
        public virtual int Age { get; set; }
        public virtual string FirstName { get; set; }
        public virtual string LastName { get; set; }
    }

My Controller

         private readonly UserAccountService<CustomUserAccount> _userAccountService;
         private readonly AuthenticationService<CustomUserAccount> _authService;

        public UserAccountController(UserAccountService<CustomUserAccount> userAccountService,AuthenticationService<CustomUserAccount> authSvc)
        {
            _userAccountService = userAccountService;
            _authService = authSvc;
        }

I saw that I needed to create a custom database class which looks like

      public class MigrationsContextFactory : IDbContextFactory<CustomDatabase>
    {
        public CustomDatabase Create()
        {
            return new CustomDatabase("MembershipDb");
        }
    }

    public class CustomDatabase : MembershipRebootDbContext<CustomUserAccount, CustomGroup>
    {

       
        public CustomDatabase(string name):base(name)
        {
        }

       
    }

I am using autofac in my project so I have tried to configure multiple ways within my startup.cs

                private static void BuildAutofacContainer(IAppBuilder app, string authType)
        {
            var builder = new ContainerBuilder();

            var config = CreateMembershipRebootConfiguration(app);

            builder.RegisterInstance(config).As<MembershipRebootConfiguration>();

            builder.RegisterType<DefaultMembershipRebootDatabase>()
                .InstancePerLifetimeScope();

            builder.RegisterType<DefaultUserAccountRepository>()
                .As<IUserAccountRepository>()
                .As<IUserAccountRepository<RelationalUserAccount>>()
                .As<IUserAccountQuery>()
                .As<IUserAccountQuery<BrockAllen.MembershipReboot.Relational.RelationalUserAccount>>()
                .InstancePerLifetimeScope();

            builder.RegisterType<DefaultUserAccountRepository>()
              .As<IUserAccountRepository>()
              .InstancePerLifetimeScope();

            //My registrations
            
            builder.RegisterType<UserAccountService<CustomUserAccount>>().InstancePerLifetimeScope();
            builder.RegisterType<AuthenticationService<CustomUserAccount>>().InstancePerLifetimeScope();

            //tried these but dont work
            //builder.RegisterType<CustomUserService>().As<IUserService>().InstancePerLifetimeScope();
        
            //builder.RegisterType<CustomUserRepository>().As<IUserAccountRepository<CustomUserAccount>>()
            //    .InstancePerLifetimeScope();

            //builder.RegisterType<CustomUserAccount>()
            //    .As<CustomUserRepository>()
            //    .InstancePerRequest();doesnt work

            //builder.RegisterInstance(config)
            //    .As<MembershipRebootConfiguration<CustomUserAccount>>();
            
            
            
            //end

            builder.RegisterType<CustomUserRepository>()
                .As<IUserAccountRepository<CustomUserAccount>>()
                .InstancePerRequest();

            builder.RegisterType<CustomDatabase>()
                .AsSelf()
                .InstancePerRequest();

            builder.RegisterType<CustomUserRepository>()
                .As<IUserAccountQuery>()
                .InstancePerRequest();
   
            builder.RegisterType<UserAccountService>().OnActivating(e =>
            {
                var owin = e.Context.Resolve<IOwinContext>();
                var debugging = false;
    #if DEBUG
                debugging = true;
    #endif
                e.Instance.ConfigureTwoFactorAuthenticationCookies(owin.Environment, debugging);
            })
            .AsSelf()
            .InstancePerLifetimeScope();

            builder.RegisterType<UserAccountService<RelationalUserAccount>>().OnActivating(e =>
            {
                var owin = e.Context.Resolve<IOwinContext>();
                var debugging = false;
    #if DEBUG
                debugging = true;
    #endif
                e.Instance.ConfigureTwoFactorAuthenticationCookies(owin.Environment, debugging);
            })
            .AsSelf()
            .InstancePerLifetimeScope();

            builder.Register(ctx =>
            {
                var owin = ctx.Resolve<IOwinContext>();
                return new OwinAuthenticationService(authType, ctx.Resolve<UserAccountService>(), owin.Environment);
            })
            .As<AuthenticationService>()
            .InstancePerLifetimeScope();

            builder.Register(ctx => HttpContext.Current.GetOwinContext()).As<IOwinContext>();
            builder.RegisterControllers(typeof(Startup).Assembly);

            var container = builder.Build();
            System.Web.Mvc.DependencyResolver.SetResolver(new AutofacDependencyResolver(container));
        }

What am I missing with my setup? I get an error of 
       None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'NS.Account.MembershipReboot.CustomDatabase' can be invoked with the available services and parameters:
Cannot resolve parameter 'System.String name' of constructor 'Void .ctor(System.String)'.

Any suggestions on whats wrong with how I have set things up would be hugely appreciated

**Comment by brockallen** [comment]
Sounds like the DI can't create the DbContext because of your ctor param -- you need to register a delegate instead to create your DbContext class where you can pass the name.

**Comment by shaneprice** [comment]
Thanks Brock, By any chance are any of the samples doing something like this? I'm just not too sure where to start looking

**Comment by brockallen** [comment]
Some of the MR samples do this with the DbContext class -- this issue is more of an autofac question and not a MR question, to be honest.

**Comment by shaneprice** [comment]
Ok Thank you, I will take a hunt around
