### ISSUE TITLE
Handling 'RequireAccountVerification' when federating across multiple IdPs

### ISSUE THREAD

**Issue by ciaranj** [IdentityServer/IdentityServer3.MembershipReboot#32]
So :/  I wonder if it's possible to somehow change the 'RequreAccountVerification' property of the active membershiprebootconfiguration based on the 'idp' doing the actual authentication.

What I mean by this is I would ideally like my local users to require an email address that is verified, but if they've authenticated from, lets say, twitter I'm less bothered.   (Similar to #20 but for handling the case where an IdP cannot provide an e-mail) Is  this possible/reasonable or should I effectively create my own UserService that lets me change that requirement dynamically ?

**Comment by brockallen** [comment]
Well, if they're authenticing from an external IdP, you can always set the user's email as verified (assuming you trust twitter, etc. to have already validated the email). There's an API on the user account service to set the verified email.

**Comment by ciaranj** [comment]
Indeed, my issue is however that the 3rd party (twitter in this case) will *never* provide the e-mail, so I'd like to 'adjust' the semantics of the Membershipreboot library (in this case 'requires verified email') depending on the IDP federated onto.  I can see how I *could* probably achieve this, but wonder if its relevant to the general library?

**Comment by brockallen** [comment]
I'm confused -- if the user authenticates w/ twitter then the MR Authenticate API is not used and that's where the RequreAccountVerification is checked (unless I'm forgetting something).

**Comment by ciaranj** [comment]
When the call comes back in from twitter, it still passes through ProcessNewExternalAccountAsync which  (if MR is configured so) requires an e-mail address to be present in the claims, I'd like that bit, just there to be tweakable depending on my whims ?

**Comment by brockallen** [comment]
Yea, if this is being enforced by the MR user service, then just tweak that how you like it.

**Comment by ciaranj** [comment]
yeah I've spent a chunk of time getting my head around (it's been a while since I've been in the IdSrv internals) registration and I now know how I can get my per-request bits and pieces routed into the relevant place so should be able to do what I need with a facade around it I think :) ty.
