### ISSUE TITLE
Nuget package Install on ASP.NET 5 web app fails

### ISSUE THREAD

**Issue by ninety7** [IdentityServer/IdentityServer3.MembershipReboot#34]
When installing the latest version (2.0.0) on a ASP.NET 5 app, the cs file is never copied to the project.

**Comment by leastprivilege** [comment]
The new nuget does not support source code packages anymore? But why would you do that anyways?

**Comment by ninety7** [comment]
I don't understand your question very well. I read that the new NuGet does not support transformations. Does this mean that this package is useless on ASP.NET 5 projects?

**Comment by brockallen** [comment]
The 2.0 version of this NuGet does not ship an assembly -- instead we ship a .cs source file that you can use/modify. @leastprivilege 's question is if NuGet on ASP.NET 5 does not support source code packages? Try to create a ASP.NET 4.5 host and install it to see how that works.

**Comment by ninety7** [comment]
@brockallen @leastprivilege Now I understand your question. The answer is that source code transformations are not supported on nuget packages for ASP.NET 5 projects, sadly. I'll copy the source code file for now; just let me know if you have any plans on supporting this new ASP.NET version.

**Comment by brockallen** [comment]
well, that stinks

**Comment by leastprivilege** [comment]
We will publish the source code files as gists for the time being. Source code support is coming back according to the nuget blog
