### ISSUE TITLE
UTC offset applied twice to updated_at claim

### ISSUE THREAD

**Issue by SteelsenS** [IdentityServer/IdentityServer3.MembershipReboot#37]
When returning a user profile the `updated_at` claim is off from the correct UTC value by the user's time offset.

E.g., user Bob has a LastUpdated date in the database of 
`2015-11-19T22:17:31` (UTC)
The `updated_at` claim returns `11447989451` (UTC, obviously) which in human friendly form is
`2015-11-20T03:17:31`

It appears to be because in [`GetClaimsFromAccount`](https://github.com/IdentityServer/IdentityServer3.MembershipReboot/blob/master/source/IdentityServer3.MembershipReboot/IdentityServer3.MembershipReboot.cs#L73) the following is called:

```csharp
new Claim(Constants.ClaimTypes.UpdatedAt, IdentityModel.EpochTimeExtensions.ToEpochTime(account.LastUpdated).ToString(), ClaimValueTypes.Integer),
```
The date, which is already in UTC, is sent to [`ToEpochTime`](https://github.com/IdentityModel/Thinktecture.IdentityModel/blob/master/source/Client.Shared/EpochTimeExtensions.cs#L15) in the IdentityModel library which then applies the UTC offset again:

```csharp
public static long ToEpochTime(this DateTime dateTime)
{
   var date = dateTime.ToUniversalTime();
   var ticks = date.Ticks - new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc).Ticks;
   var ts = ticks / TimeSpan.TicksPerSecond;
   return ts;
}
```
Resulting in UTC +5hrs (the current offset for my region) or 03:17 on 2015-11-20.

This can be replicated in the samples library. I launched the MembershipReboot sample and created a sample account for Bob:

```sql
SELECT [ID]
      ,[Username]
      ,[Created]
      ,[LastUpdated]
  FROM [IdentityServer3.MembershipReboot].[dbo].[UserAccounts]
```
```
ID                                   Username  Created                 LastUpdated
------------------------------------ --------  ----------------------- ------------
030493FF-C202-42E1-A372-C761F626A8B9 bob       2015-11-19 22:17:31.650 2015-11-19 22:17:31.650
```
And then used the WPF Implicit client to log in with profile and access token, called the userInfo endpoint and got back:
```json
{
  "sub": "030493ff-c202-42e1-a372-c761f626a8b9",
  "updated_at": 1447989451,
  "preferred_username": "bob"
}
```
As noted above, that epoch time corresponds to five hours ahead of the UTC time stored in the database.

I'm not sure if the solution is to add another epoch method to the IdentityModel library that skips the offset or to perform an offset either before or after sending the time to that method. (Or if I've missed something completely and this is a non-issue). For my own purposes I've overridden `GetClaimsFromAccount` and use a different epoch conversion function.

**Comment by brockallen** [comment]
Ok, good catch. Do you think this is a problem in MR itself, or in the MR/IdSvr integration?

**Comment by SteelsenS** [comment]
Doesn't seem to be MR. I double checked the CustomUserAccount sample in the main MR repository and confirmed that in the user account's LastUpdated property the DateTimeKind is set properly and calling ToUniversalTime works as expected. I'll root around the integration to see where this might be happening.

**Comment by brockallen** [comment]
Ok, thx. Mind sending a PR?

**Comment by SteelsenS** [comment]
FYI, started looking at this again, right now I'm suspecting EF (something like [this](http://stackoverflow.com/questions/29496306/how-to-specify-that-datetime-objects-retrieved-from-entityframework-should-be-da)) but such an issue should be more consistent. If I figure it out I'll send a PR, should have more time over the next week.

**Comment by brockallen** [comment]
Any update?

**Comment by SteelsenS** [comment]
Dropped off my radar - will pick back up unless someone sees something
obvious.



__________________________
Steelsen Smith
(203) 516-0406

**Comment by SteelsenS** [comment]
It seems like this is an MR/EF issue after all. An `Update(account)` operation in the User Service sets the `Kind` property properly to "UTC," but on first retrieval the property is set to "Unspecified." I'm assuming this affects all DateTime type properties.

I set up a sample solution to demonstrate [here](https://github.com/SteelsenS/MR_Dtk_Issue)

This can be "fixed" for the purposes of IdSrv/MR integration by setting the property value manually in [`GetClaimsFromAccount()`](https://github.com/IdentityServer/IdentityServer3.MembershipReboot/blob/master/source/IdentityServer3.MembershipReboot/IdentityServer3.MembershipReboot.cs#L73). 

If this hasn't been / isn't a problem in MR then that minor change would be the path of least resistance.

Otherwise, this becomes an MR issue. The root cause is that EF doesn't allow you to specify a default Kind for DateTime. This has been discussed multiple times on SO, e.g., [here](http://stackoverflow.com/questions/4648540/entity-framework-datetime-and-utc), [here](http://stackoverflow.com/questions/29496306/how-to-specify-that-datetime-objects-retrieved-from-entityframework-should-be-da), [here](http://stackoverflow.com/questions/1906331/making-sure-that-datetime-properties-return-datetimekind-utc).

Options to remedy are essentially:
1. Switch to DateTimeOffset from DateTime (this is being discussed separately here brockallen/BrockAllen.MembershipReboot#388)
2. Modify the accessor of DateTime properties to set the `Kind` property
3. Modify the dbContext to respect a new attribute for datetime kind on account properties
4. Modify the dbContext to enforce a UTC datetime kind on all datetime values retrieved from the DB

All of these could have side effects depending on how people are using DateTime values. (1) is a breaking change, (2) and (3) could affect people overriding the base Created/Updated/etc. properties, (4) could cause unexpected behavior for people who have extended `RelationalUserAccount` with custom DateTime properties that are for some reason not persisted in UTC.

Do you think this should be patched here by setting the `Kind` property after retrieval or would it be better to move this issue to the main MR repository?

**Comment by SteelsenS** [comment]
@brockallen - any thoughts on whether to open as an MR issue or just patch the behavior here?

**Comment by brockallen** [comment]
Sorry this fell thru... sounds like easiest approach is to set Kind to UTC when reading from DB in MR, no? So in short, correct the data as it's being read to match the assumption going in.

**Comment by SteelsenS** [comment]
Sounds reasonable. In that case this is no longer an MR/IDSrv issue. I'll close this and reopen in the main MR repo.
