### ISSUE TITLE
adding identityserver3.membershipreboot package in aspnet 5 applications

### ISSUE THREAD

**Issue by srivch** [IdentityServer/IdentityServer3.MembershipReboot#38]
when i add identityserver3.membershipreboot package in a aspnet 5 application, i am not able to access the namespace identityserver3.membershipreboot, i only get identityserver3.core. So do i manually include the class MembershipRebootUserService in order to use it?

**Comment by brockallen** [comment]
I think in an ASP.NET 5 project they don't support source file NuGets.

**Comment by srivch** [comment]
thanks
