### ISSUE TITLE
Potential security issue: Authentication implementation leaks details about existing user accounts

### ISSUE THREAD

**Issue by gingters** [IdentityServer/IdentityServer3.MembershipReboot#40]
When using IdentityServer3.MembershipReboot v2.0.0 together with the latest version 2.4.0 of IdentityServer3, the following behaviour can be noticed:

When trying to authenticate, the current MembershipReboot implementation leaks information whether a user account exists or not. This can be determined by the time that passes. When there is no user account for the given user name, the response `invalid_grant` is received almost immediately.

When a user account exists for the given user name, the response takes significantly longer.

**Comment by brockallen** [comment]
This has always been a well known behavior. MR doesn't know if you're allowing public registrations, which is a pretty easy way to see if an account already exists or not. If you don't allow public registrations and want to mask the password hashing timings, then put in a time constant implementation in the password validation. This was asked recently on the MR issue tracker.

**Comment by gingters** [comment]
Ah, okay. Fine then. Thanks for the clarification.
