### ISSUE TITLE
Configuring MR for Authentication Audit Event Handler

### ISSUE THREAD

**Issue by crammer** [IdentityServer/IdentityServer3.MembershipReboot#41]
Hi,

I was able to configure EmailAccountEventsHandler in MR.  I am having challenges wiring up AuthenticationAuditEventHandler and NotifyAccountOwnerWhenTooManyFailedLoginAttempts in my OWIN project.  Any guidance is much appreciated.

Thank you.

**Comment by brockallen** [comment]
Did they work in the sample?

**Comment by crammer** [comment]
Yes with additional codes from CustomizationsSample project in Membership sample

**Comment by brockallen** [comment]
So then copy what's working from the sample. I don't know what else to offer/suggest.
