### ISSUE TITLE
Claims Being Dropped

### ISSUE THREAD

**Issue by rmmoore80** [IdentityServer/IdentityServer3.MembershipReboot#47]
I have a small project that uses IdentityServer3 w/ MembershipReboot (Thanks for the recommendation here Brock). I was utilizing a few claims in my client application, one being "sub" and another being a custom claim. All was working fine. I updated the nuget packages today to bring IdentityServer3.MembershipReboot up to version 2.0.0, BrockAllen.MembershipReboot up to 8.4 and IdentityServer3 up to 2.5.1. After the update, several claims have been dropped from the principal. I debugged the situation and the claims are being retrieved and properly added in the MR services (and my CustomClaimMapping class). Once the execution reaches line 141 in IdentityServer3.MembershipReboot.cs the await call is executed and nothing is returned and about 7 claims are dropped. I am trying to determine if they are being dropped even earlier.

**Comment by brockallen** [comment]
Keep debugging and let us know, please.

**Comment by brockallen** [comment]
Any update?

**Comment by rmmoore80** [comment]
Investigating possible configuration issues.

**Comment by rmmoore80** [comment]
You can close. This was a combo of some old custommapping logic and bad scope/claim configuration data.
